# Pages CMS Configuration
# Docs: https://pagescms.org/docs

title: Simon Bromander
logo: public/images/logo.png  # Adjust if you have a logo in a different location

media:
  input: public/images
  output: /images

content:
  - name: blog
    label: Blog Posts
    type: collection
    path: public/content/blog/
    view:
      fields: [title, date, author]
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: date
        label: Publish Date
        type: date
        required: true
      - name: author
        label: Author
        type: string
        default: Simon Bromander
      - name: thumbnail
        label: Featured Image
        type: image
        required: false
      - name: excerpt
        label: Excerpt
        type: text
      - name: body
        label: Content
        type: rich-text
    filename: '{{yyyy}}-{{MM}}-{{dd}}-{{slug}}.md'
    hooks:
      afterChange: npm run generate-blog-index 